coverage:
  status:
    project:
      default:
        threshold: 0.1%
    patch:
      default:
        threshold: 0.1%
  ignore:
  - "internal/turbokeeperkafka/mock_sarama" # Generated mock
  - "internal/turbokeeperauth/turbokeeperauthtest" # Mock
  - "cmd/plugins.go" # Not testable with UTs
